In [1]:
import numpy as np
import numpy.random as random

# 小数点3桁まで表示
%precision 3



'%.3f'

In [5]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [6]:
data.dtype

dtype('int64')

In [7]:
print("Dimentions : {0}".format(data.ndim))
print("Elements : {0}".format(data.size))

Dimentions : 1
Elements : 10


In [8]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [9]:
data_a = np.array([i for i in range(5, 11)])
data_b = np.array([j for j in range(10, 16)])
data_b * data_a

array([ 50,  66,  84, 104, 126, 150])

In [10]:
data_b / data_a

array([2.   , 1.833, 1.714, 1.625, 1.556, 1.5  ])

In [11]:
data_a **2

array([ 25,  36,  49,  64,  81, 100])

In [12]:
data[::-1]

array([ 5,  1,  8,  7,  6, 10,  4,  3,  2,  9])

In [15]:
data.sort()
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
data[::-1].sort()
print(data)

[10  9  8  7  6  5  4  3  2  1]


In [17]:
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
data.max()

10

In [19]:
data.min()

1

In [20]:
data.ave()

AttributeError: 'numpy.ndarray' object has no attribute 'ave'

In [21]:
data.sum()

55

In [22]:
data.cumsum()

array([10, 19, 27, 34, 40, 45, 49, 52, 54, 55])

In [25]:
data.cumsum() / data.sum() * 100.0

array([ 18.182,  34.545,  49.091,  61.818,  72.727,  81.818,  89.091,
        94.545,  98.182, 100.   ])

In [26]:
import numpy.random as random
random.seed(0)

In [27]:
# μ(0, 1)の正規分布乱数を100件取得
rnd_data = random.randn(100)
print(rnd_data)

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411
  0.144  1.454  0.761  0.122  0.444  0.334  1.494 -0.205  0.313 -0.854
 -2.553  0.654  0.864 -0.742  2.27  -1.454  0.046 -0.187  1.533  1.469
  0.155  0.378 -0.888 -1.981 -0.348  0.156  1.23   1.202 -0.387 -0.302
 -1.049 -1.42  -1.706  1.951 -0.51  -0.438 -1.253  0.777 -1.614 -0.213
 -0.895  0.387 -0.511 -1.181 -0.028  0.428  0.067  0.302 -0.634 -0.363
 -0.672 -0.36  -0.813 -1.726  0.177 -0.402 -1.63   0.463 -0.907  0.052
  0.729  0.129  1.139 -1.235  0.402 -0.685 -0.871 -0.579 -0.312  0.056
 -1.165  0.901  0.466 -1.536  1.488  1.896  1.179 -0.18  -1.071  1.054
 -0.403  1.222  0.208  0.977  0.356  0.707  0.011  1.786  0.127  0.402]


In [28]:
# Abstract Target Data
data_sample = np.array([9, 2, 1, 4, 3, 5, 8, 7, 6, 0])
print("Size : {0}".format(data_sample.size))

Size : 10


In [29]:
# Random Sampling
print(random.choice(data_sample, 5))

[9 3 0 8 5]


In [39]:
for i in range(5):
    print(random.choice(data_sample, 5))

[9 2 0 2 8]
[0 6 8 4 9]
[7 4 1 5 0]
[7 4 3 7 8]
[7 4 8 0 4]


In [40]:
for i in range(5):
    print(random.choice(data_sample, 5, replace=False))

[3 6 9 8 1]
[9 7 0 1 8]
[3 1 9 8 2]
[0 4 8 6 9]
[8 9 0 2 7]


In [42]:
random.choice(data_sample, 5, replace=False) * random.choice(data_sample, 5, replace=True)

array([ 7, 36,  7, 18, 40])

In [43]:
# Matrix
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
data_A = np.arange(9).reshape(3,3)
print(data_A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
data_ones = np.ones(9).reshape(3,3)
print(data_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
data_zeros = np.zeros(9).reshape(3,3)
print(data_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
np.dot(data_ones, data_A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [57]:
np.dot(data_A, data_ones)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])