In [3]:
import numpy as np
import numpy.random as random

# Practice 2-1
np.array([i for i in range(51)]).sum()

1275

In [11]:
# Practice 2-2
random.seed(0)
data  = random.randn(10)
print(data)
print("Max : {0}".format(data.max()))
print("Min : {0}".format(data.min()))
print("Sum : {0}".format(data.sum()))

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
Max : 2.240893199201458
Min : -0.977277879876411
Sum : 7.380231707288347


In [15]:
# Practice 2-3
data_three = np.ones(25).reshape(5,5) * 3
print(data_three)
data_three * data_three

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])