In [1]:
import numpy as np
import scipy.linalg as linalg


# Practice 2-4
matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(linalg.det(matrix))

-12.000000000000002


In [4]:
# Practice 2-5
inv_matrix = linalg.inv(matrix)
print(inv_matrix)
eig_value, eig_vector = linalg.eig(matrix)
print(eig_value)
print(eig_vector)

[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
[ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [6]:
# Practice 2-6
from scipy.optimize import newton

def my_func(x: float) -> float:
    return x**3 + 2*x + 1

newton(my_func,0)

-0.45339765151640365