In [5]:
import numpy as np
import scipy.linalg as linalg


# Matrix Determinant
matrix = np.array([[1, -1, -1],[-1,1,-1],[-1,-1,1]])
print(matrix)
print(linalg.det(matrix))

# Matrix Inverse
matrix_inv = linalg.inv(matrix)
print(matrix_inv)
print(np.dot(matrix, matrix_inv))

[[ 1 -1 -1]
 [-1  1 -1]
 [-1 -1  1]]
-4.0
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Eigen Value, Vector
eig_v, eig_vec = linalg.eig(matrix)

In [7]:
print("Eigen Value : {0}".format(eig_v))
print("Eigen Vector : {0}".format(eig_vec))

Eigen Value : [-1.+0.j  2.+0.j  2.+0.j]
Eigen Vector : [[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


In [13]:
# Newton Method
from scipy.optimize import newton

def my_func(x: float) -> float:
    return (x**2+ 2*x + 1)

print(newton(my_func, 0))


-0.999999985174924


In [14]:
# min
from scipy.optimize import minimize_scalar

print(minimize_scalar(my_func, method='Brent'))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002
